### ISSUE TITLE
GUI not reflecting parameter changes

### ISSUE THREAD

**Issue by bladeSk** [bsutherland/JuceOPLVSTi#28]
The GUI does not refresh when you change the parameters via MIDI CCs or automation. Other VSTs seem to do that and it's useful. After playing with MIDI knobs, the GUI is showing something entirely different than what you're hearing.

**Comment by bsutherland** [comment]
Thanks for the report. I'll see what I can do.

**Comment by bsutherland** [comment]
Well, it only took two years, but hopefully this is fixed in 0.14.2!

**Comment by bladeSk** [comment]
Thanks! The new UI looks great. However, it still doesn't update in Ableton. The sound changes, but UI doesn't :/ I just tried it with the XY control, which sends automation messages.

![image](https://cloud.githubusercontent.com/assets/4263742/23579178/1c20996c-00e8-11e7-97ca-5f8b4dcc7be1.png)

**Comment by bsutherland** [comment]
I see, thanks! I misunderstood the issue. I'll see what I can do.

**Comment by linus369** [comment]
Would be really great to see this issue been fixed - I am also on Ableton. Much more fun to use VST's with external MIDI controller - so hoping for working UI response of JuceOPL for quiete a long time :)

Besides of that, lovely piece of music software, thanks!

**Comment by bsutherland** [comment]
I recently found out about an excellent project called ADLplug. It is maintained, has builds for Windows and OSX, and does everything which JuceOPLVSTi does and more. I believe that it may support the feature you're hoping for. In case you're interested:

https://github.com/jpcima/ADLplug

**Comment by bsutherland** [comment]
This has finally been fixed thanks to a contribution from @Windfisch in release 1.0.1
